## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Alex Aritan"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  logo = "images/hungary.jpg"
  favicon = true
  subtitle = "Software engineer. Astrophotographer. Auto enthusiast."

[Params.spotlight1]
  title = "Software"
  description = "I develop TypeScript/JavaScript REST APIs, GraphQL APIs, React UIs, standalone libraries, and more. I prioritize efficient implementation with readable, documented code and thorough test suites. Innovation and open-source software provide me tons of inspiration."
  image = "images/code.jpg"

[Params.spotlight2]
  title = "Astrophotography"
  description = "Galaxies and nebulas are beautiful deep space objects that are often hiding in plain sight."
  image = "images/andromeda.png"
  url = "https://aritan.space"
  buttonText = "Check out my photos"

[Params.spotlight3]
  title = "Automotive"
  description = "Nothing gets the adrenaline going quite like driving a car as fast as it will let you."
  image = "images/lamborghini.jpg"
  url = "https://www.youtube.com/watch?v=8Ifty7qiw7g"
  buttonText = "Go fast"

[Params.social]
  github = "https://github.com/alexaritan/"